
import { Movie, MovieGenre, MovieRegion, Comment, User, NewsItem } from './types';

/**
 * 预设用户信息
 */
export const MOCK_USERS: User[] = [
  { id: '1', username: '管理员', password: 'password', role: 'admin', avatar: 'https://ui-avatars.com/api/?name=Admin&background=random' },
  { id: '2', username: '电影发烧友', password: 'password', role: 'user', avatar: 'https://ui-avatars.com/api/?name=User&background=random' }
];

/**
 * 电影库模拟数据（包含 39 部经典电影）
 */
export const MOCK_MOVIES: Movie[] = [
  {
    id: 'm1',
    title: '肖申克的救赎',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg',
    genre: [MovieGenre.Drama, MovieGenre.Crime],
    releaseDate: '1994-09-10',
    region: MovieRegion.Hollywood,
    director: '弗兰克·德拉邦特',
    actors: ['蒂姆·罗宾斯', '摩根·弗里曼', '鲍勃·冈顿'],
    description: '20世纪40年代末，小有成就的青年银行家安迪（蒂姆·罗宾斯 Tim Robbins 饰）因涉嫌杀害妻子及她的情人 alert 而锒铛入狱。',
    rating: 9.7,
    collectCount: 24530,
    ratingDistribution: { 5: 95, 4: 4, 3: 1, 2: 0, 1: 0 },
    keywords: [{ text: '自由', value: 100 }, { text: '希望', value: 90 }, { text: '经典', value: 95 }, { text: '人性', value: 80 }, { text: '救赎', value: 85 }]
  },
  {
    id: 'm3',
    title: '盗梦空间',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg',
    genre: [MovieGenre.SciFi, MovieGenre.Action],
    releaseDate: '2010-09-01',
    region: MovieRegion.Hollywood,
    director: '克里斯托弗·诺兰',
    actors: ['莱昂纳多·迪卡普里奥', '约瑟夫·高登-莱维特', '艾伦·佩吉'],
    description: '道姆·柯布（莱昂纳多·迪卡普里奥 Leonardo DiCaprio 饰）与同事阿瑟（约瑟夫·高登-莱维特 Joseph Gordon-Levitt 饰）在一次盗梦行动中失败。',
    rating: 9.3,
    collectCount: 15400,
    ratingDistribution: { 5: 85, 4: 10, 3: 3, 2: 1, 1: 1 },
    keywords: [{ text: '烧脑', value: 100 }, { text: '梦境', value: 95 }, { text: '诺兰', value: 90 }, { text: '科幻', value: 85 }, { text: '创意', value: 80 }]
  },
  {
    id: 'm4',
    title: '千与千寻',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png',
    genre: [MovieGenre.Animation, MovieGenre.SciFi],
    releaseDate: '2001-07-20',
    region: MovieRegion.JapanKorea,
    director: '宫崎骏',
    actors: ['柊瑠美', '入野自由', '夏木真理'],
    description: '千寻和爸爸妈妈一同驱车前往新家，在郊外的小路上不慎进入了神秘的隧道——他们去到了另外一个诡异世界。',
    rating: 9.4,
    collectCount: 21000,
    ratingDistribution: { 5: 88, 4: 10, 3: 2, 2: 0, 1: 0 },
    keywords: [{ text: '宫崎骏', value: 100 }, { text: '治愈', value: 95 }, { text: '成长', value: 90 }, { text: '童话', value: 85 }, { text: '唯美', value: 80 }]
  },
  {
    id: 'm5',
    title: '泰坦尼克号',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png',
    genre: [MovieGenre.Romance, MovieGenre.Drama],
    releaseDate: '1998-04-03',
    region: MovieRegion.Hollywood,
    director: '詹姆斯·卡梅隆',
    actors: ['莱昂纳多·迪卡普里奥', '凯特·温丝莱特'],
    description: '1912年4月10日，号称 “世界工业史上的奇迹”的豪华客轮泰坦尼克号开始了自己的处女航。',
    rating: 9.4,
    collectCount: 19500,
    ratingDistribution: { 5: 85, 4: 12, 3: 2, 2: 1, 1: 0 },
    keywords: [{ text: '爱情', value: 100 }, { text: '经典', value: 95 }, { text: '感人', value: 90 }, { text: '灾难', value: 70 }, { text: '大片', value: 80 }]
  },
  {
    id: 'm6',
    title: '龙猫',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/0/02/My_Neighbor_Totoro_-_Tonari_no_Totoro_%28Movie_Poster%29.jpg',
    genre: [MovieGenre.Animation, MovieGenre.Comedy],
    releaseDate: '1988-04-16',
    region: MovieRegion.JapanKorea,
    director: '宫崎骏',
    actors: ['日高法子', '坂本千夏'],
    description: '小月的母亲生病住院了，父亲带着她与四岁的妹妹小梅到乡间的居住。',
    rating: 9.2,
    collectCount: 16700,
    ratingDistribution: { 5: 80, 4: 15, 3: 4, 2: 1, 1: 0 },
    keywords: [{ text: '童年', value: 100 }, { text: '可爱', value: 90 }, { text: '自然', value: 80 }, { text: '纯真', value: 85 }]
  },
  {
    id: 'm7',
    title: '教父',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg',
    genre: [MovieGenre.Crime, MovieGenre.Drama],
    releaseDate: '1972-03-24',
    region: MovieRegion.Hollywood,
    director: '弗朗西斯·福特·科波拉',
    actors: ['马龙·白兰度', '阿尔·帕西诺'],
    description: '40年代的美国，“教父”维托·唐·柯里昂（马龙·白兰度 饰）是黑手党柯里昂家族的首领。',
    rating: 9.3,
    collectCount: 14200,
    ratingDistribution: { 5: 92, 4: 6, 3: 2, 2: 0, 1: 0 },
    keywords: [{ text: '黑帮', value: 100 }, { text: '家族', value: 90 }, { text: '权利', value: 85 }, { text: '经典', value: 95 }]
  },
  {
    id: 'm8',
    title: '楚门的世界',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cd/Trumanshow.jpg',
    genre: [MovieGenre.Drama, MovieGenre.SciFi],
    releaseDate: '1998-06-05',
    region: MovieRegion.Hollywood,
    director: '彼得·威尔',
    actors: ['金·凯瑞', '劳拉·琳妮'],
    description: '楚门（金•凯瑞 Jim Carrey 饰）是一个平凡得不能再平凡的人。',
    rating: 9.3,
    collectCount: 18100,
    ratingDistribution: { 5: 88, 4: 10, 3: 2, 2: 0, 1: 0 },
    keywords: [{ text: '生活', value: 95 }, { text: '真相', value: 100 }, { text: '讽刺', value: 85 }, { text: '自由', value: 90 }]
  },
  {
    id: 'm9',
    title: '星际穿越',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg',
    genre: [MovieGenre.SciFi, MovieGenre.Drama],
    releaseDate: '2014-11-07',
    region: MovieRegion.Hollywood,
    director: '克里斯托弗·诺兰',
    actors: ['马修·麦康纳', '安妮·海瑟薇', '杰西卡·查斯坦'],
    description: '近未来的地球黄沙遍野，小麦、秋葵等基础农作物相继因枯萎病灭绝。',
    rating: 9.4,
    collectCount: 22000,
    ratingDistribution: { 5: 90, 4: 8, 3: 1, 2: 1, 1: 0 },
    keywords: [{ text: '太空', value: 100 }, { text: '物理', value: 85 }, { text: '亲情', value: 95 }, { text: '诺兰', value: 90 }, { text: '震撼', value: 88 }]
  },
  {
    id: 'm10',
    title: '蝙蝠侠：黑暗骑士',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
    genre: [MovieGenre.Action, MovieGenre.Crime],
    releaseDate: '2008-07-18',
    region: MovieRegion.Hollywood,
    director: '克里斯托弗·诺兰',
    actors: ['克里斯蒂安·贝尔', '希斯·莱杰', '艾伦·艾克哈特'],
    description: '从亲眼目睹父母被人杀死的阴影中走出来的“蝙蝠侠”，经历了成长之后。',
    rating: 9.2,
    collectCount: 19800,
    ratingDistribution: { 5: 88, 4: 10, 3: 2, 2: 0, 1: 0 },
    keywords: [{ text: '小丑', value: 100 }, { text: '英雄', value: 90 }, { text: '黑暗', value: 85 }, { text: '人性', value: 80 }]
  },
  {
    id: 'm11',
    title: '阿甘正传',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg',
    genre: [MovieGenre.Drama, MovieGenre.Romance],
    releaseDate: '1994-07-06',
    region: MovieRegion.Hollywood,
    director: '罗伯特·泽米吉斯',
    actors: ['汤姆·汉克斯', '罗宾·怀特'],
    description: '阿甘（汤姆·汉克斯 饰）于二战结束后不久出生在美国南方阿拉巴马州一个闭塞的小镇。',
    rating: 9.5,
    collectCount: 23100,
    ratingDistribution: { 5: 93, 4: 6, 3: 1, 2: 0, 1: 0 },
    keywords: [{ text: '励志', value: 100 }, { text: '人生', value: 95 }, { text: '奔跑', value: 90 }, { text: '经典', value: 85 }]
  },
  {
    id: 'm12',
    title: '你的名字',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png',
    genre: [MovieGenre.Animation, MovieGenre.Romance],
    releaseDate: '2016-08-26',
    region: MovieRegion.JapanKorea,
    director: '新海诚',
    actors: ['神木隆之介', '上白石萌音'],
    description: '在远离大都会的小山村，住着巫女世家出身的高中女孩宫水三叶。',
    rating: 8.5,
    collectCount: 16500,
    ratingDistribution: { 5: 60, 4: 30, 3: 8, 2: 2, 1: 0 },
    keywords: [{ text: '唯美', value: 100 }, { text: '爱情', value: 90 }, { text: '时空', value: 85 }, { text: '新海诚', value: 95 }]
  },
  {
    id: 'm13',
    title: '美丽人生',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7c/Vitaebella.jpg',
    genre: [MovieGenre.Drama, MovieGenre.Comedy],
    releaseDate: '1997-12-20',
    region: MovieRegion.Europe,
    director: '罗伯托·贝尼尼',
    actors: ['罗伯托·贝尼尼', '尼可莱塔·布拉斯基'],
    description: '犹太青年圭多（罗伯托·贝尼尼 饰）来到意大利小镇。他爱上了美丽的姑娘多拉。',
    rating: 9.6,
    collectCount: 21500,
    ratingDistribution: { 5: 92, 4: 6, 3: 1, 2: 1, 1: 0 },
    keywords: [{ text: '父爱', value: 100 }, { text: '战争', value: 95 }, { text: '乐观', value: 90 }, { text: '经典', value: 85 }]
  },
  {
    id: 'm14',
    title: '寻梦环游记',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg',
    genre: [MovieGenre.Animation, MovieGenre.Comedy],
    releaseDate: '2017-11-22',
    region: MovieRegion.Hollywood,
    director: '李·昂克里奇',
    actors: ['安东尼·冈萨雷斯', '盖尔·加西亚·贝纳尔'],
    description: '热爱音乐的米格尔不幸地出生在一个视音乐为洪水猛兽的大家庭之中。',
    rating: 9.1,
    collectCount: 17800,
    ratingDistribution: { 5: 85, 4: 12, 3: 3, 2: 0, 1: 0 },
    keywords: [{ text: '音乐', value: 100 }, { text: '亲情', value: 95 }, { text: '梦想', value: 90 }, { text: '皮克斯', value: 85 }]
  },
  {
    id: 'm15',
    title: '阿凡达',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg',
    genre: [MovieGenre.SciFi, MovieGenre.Action],
    releaseDate: '2009-12-18',
    region: MovieRegion.Hollywood,
    director: '詹姆斯·卡梅隆',
    actors: ['萨姆·沃辛顿', '佐伊·索尔达娜', '西格妮·韦弗'],
    description: '在未来的潘多拉星球，人类为了获取珍贵的资源，启动了“阿凡达”计划。',
    rating: 8.8,
    collectCount: 21000,
    ratingDistribution: { 5: 75, 4: 18, 3: 5, 2: 1, 1: 1 },
    keywords: [{ text: '视觉', value: 100 }, { text: '特效', value: 98 }, { text: '外星', value: 85 }, { text: '史诗', value: 90 }]
  },
  {
    id: 'm16',
    title: '黑客帝国',
    coverUrl: 'https://img.goldposter.com/2015/04/The-Matrix_poster_goldposter_com_18.jpg?x-oss-process=image/resize,m_fill,h_340,w_236/quality,q_80/format,webp',
    genre: [MovieGenre.SciFi, MovieGenre.Action],
    releaseDate: '1999-03-31',
    region: MovieRegion.Hollywood,
    director: '沃卓斯基姐妹',
    actors: ['基努·里维斯', '劳伦斯·菲什伯恩', '凯瑞-安·莫斯'],
    description: '年轻的网络黑客尼奥发现看似正常的现实世界实际上是由一个名为“矩阵”的系统控制。',
    rating: 9.1,
    collectCount: 19500,
    ratingDistribution: { 5: 88, 4: 9, 3: 2, 2: 1, 1: 0 },
    keywords: [{ text: '哲学', value: 95 }, { text: '动作', value: 90 }, { text: '经典', value: 100 }, { text: '科幻', value: 92 }]
  },
  {
    id: 'm17',
    title: '低俗小说',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg',
    genre: [MovieGenre.Crime, MovieGenre.Drama],
    releaseDate: '1994-10-14',
    region: MovieRegion.Hollywood,
    director: '昆汀·塔伦蒂诺',
    actors: ['约翰·特拉沃尔塔', '乌玛·瑟曼', '塞缪尔·杰克逊'],
    description: '由三个互相关联的故事组成，讲述了洛杉矶黑帮成员的荒诞经历。',
    rating: 8.9,
    collectCount: 16800,
    ratingDistribution: { 5: 82, 4: 12, 3: 4, 2: 1, 1: 1 },
    keywords: [{ text: '昆汀', value: 100 }, { text: '非线性', value: 90 }, { text: '话痨', value: 85 }, { text: '暴力美学', value: 88 }]
  },
  {
    id: 'm18',
    title: '搏击俱乐部',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg',
    genre: [MovieGenre.Drama, MovieGenre.Action],
    releaseDate: '1999-10-15',
    region: MovieRegion.Hollywood,
    director: '大卫·芬奇',
    actors: ['布拉德·皮特', '爱德华·诺顿', '海伦娜·伯翰·卡特'],
    description: '一个患有失眠症的白领与一个卖肥皂的商人泰勒建立了“搏击俱乐部”。',
    rating: 9.0,
    collectCount: 17500,
    ratingDistribution: { 5: 85, 4: 10, 3: 3, 2: 1, 1: 1 },
    keywords: [{ text: '反叛', value: 95 }, { text: '分裂', value: 90 }, { text: '大卫芬奇', value: 88 }, { text: '震撼', value: 92 }]
  },
  {
    id: 'm19',
    title: '寄生虫',
    coverUrl: 'https://img.goldposter.com/2019/04/parasite_poster_goldposter_com_1.jpg?x-oss-process=image/resize,m_fill,h_315,w_236/quality,q_80/format,webp',
    genre: [MovieGenre.Drama, MovieGenre.Crime],
    releaseDate: '2019-05-30',
    region: MovieRegion.JapanKorea,
    director: '奉俊浩',
    actors: ['宋康昊', '李善均', '赵汝贞'],
    description: '一家四口全是无业游民的基泽家，长子基宇靠伪造文凭去富豪朴社长家应聘家教。',
    rating: 8.7,
    collectCount: 23000,
    ratingDistribution: { 5: 78, 4: 15, 3: 5, 2: 1, 1: 1 },
    keywords: [{ text: '阶级', value: 100 }, { text: '人性', value: 95 }, { text: '奥斯卡', value: 90 }, { text: '讽刺', value: 88 }]
  },
  {
    id: 'm20',
    title: '复仇者联盟4',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg',
    genre: [MovieGenre.Action, MovieGenre.SciFi],
    releaseDate: '2019-04-26',
    region: MovieRegion.Hollywood,
    director: '罗素兄弟',
    actors: ['小罗伯特·唐尼', '克里斯·埃文斯', '克里斯·海姆斯沃斯'],
    description: '幸存的复仇者们找到了穿越时间的方法，他们决定集结最后的力量逆转未来。',
    rating: 8.6,
    collectCount: 31000,
    ratingDistribution: { 5: 80, 4: 12, 3: 5, 2: 2, 1: 1 },
    keywords: [{ text: '漫威', value: 100 }, { text: '终局', value: 95 }, { text: '英雄', value: 90 }, { text: '热血', value: 85 }]
  },
  {
    id: 'm21',
    title: '狮子王',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg',
    genre: [MovieGenre.Animation, MovieGenre.Drama],
    releaseDate: '1994-06-15',
    region: MovieRegion.Hollywood,
    director: '罗杰·阿勒斯',
    actors: ['马修·布罗德里克', '詹姆斯·厄尔·琼斯', '杰瑞米·艾恩斯'],
    description: '小狮子辛巴在朋友的陪伴下逐渐成长，最终回到荣耀国夺回王位。',
    rating: 9.0,
    collectCount: 26000,
    ratingDistribution: { 5: 85, 4: 10, 3: 4, 2: 1, 1: 0 },
    keywords: [{ text: '童年', value: 100 }, { text: '成长', value: 95 }, { text: '迪士尼', value: 90 }, { text: '经典', value: 88 }]
  },
  {
    id: 'm22',
    title: '小丑',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg',
    genre: [MovieGenre.Crime, MovieGenre.Drama],
    releaseDate: '2019-10-04',
    region: MovieRegion.Hollywood,
    director: '托德·菲利普斯',
    actors: ['瓦昆·菲尼克斯', '罗伯特·德尼罗'],
    description: '亚瑟内心深处的疯狂被彻底释放，他化身为“小丑”，成为了这个混乱城市的象征。',
    rating: 8.8,
    collectCount: 20500,
    ratingDistribution: { 5: 82, 4: 11, 3: 4, 2: 2, 1: 1 },
    keywords: [{ text: '演技', value: 100 }, { text: '压抑', value: 95 }, { text: '疯狂', value: 90 }, { text: '社会', value: 85 }]
  },
  {
    id: 'm23',
    title: '疯狂动物城',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg',
    genre: [MovieGenre.Animation, MovieGenre.Comedy],
    releaseDate: '2016-03-04',
    region: MovieRegion.Hollywood,
    director: '拜伦·霍华德',
    actors: ['金妮弗·古德温', '杰森·贝特曼'],
    description: '兔子朱迪与狐狸尼克合作，解开一桩神秘的动物失踪案。',
    rating: 9.2,
    collectCount: 24000,
    ratingDistribution: { 5: 86, 4: 10, 3: 3, 2: 1, 1: 0 },
    keywords: [{ text: '可爱', value: 100 }, { text: '励志', value: 90 }, { text: '偏见', value: 85 }, { text: '迪士尼', value: 95 }]
  },
  {
    id: 'm24',
    title: '指环王：护戒使者',
    coverUrl: 'https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2197698335.webp',
    genre: [MovieGenre.Action, MovieGenre.Drama],
    releaseDate: '2001-12-19',
    region: MovieRegion.Hollywood,
    director: '彼得·杰克逊',
    actors: ['伊利亚·伍德', '伊恩·麦克莱恩', '维果·莫腾森'],
    description: '佛罗多受命带着戒指前往末日山口销毁它，以防戒指重回黑暗君主索伦手中。',
    rating: 9.1,
    collectCount: 22800,
    ratingDistribution: { 5: 88, 4: 9, 3: 2, 2: 1, 1: 0 },
    keywords: [{ text: '史诗', value: 100 }, { text: '魔幻', value: 95 }, { text: '经典', value: 90 }, { text: '震撼', value: 88 }]
  },
  {
    id: 'm25',
    title: '爱乐之城',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png',
    genre: [MovieGenre.Romance, MovieGenre.Drama],
    releaseDate: '2016-12-09',
    region: MovieRegion.Hollywood,
    director: '达米恩·查泽雷',
    actors: ['瑞恩·高斯林', '艾玛·斯通'],
    description: '在洛杉矶，米娅与钢琴家塞巴斯汀相爱，最终不得不面临分离的抉择。',
    rating: 8.4,
    collectCount: 18500,
    ratingDistribution: { 5: 70, 4: 20, 3: 6, 2: 2, 1: 2 },
    keywords: [{ text: '梦想', value: 100 }, { text: '音乐', value: 95 }, { text: '遗憾', value: 90 }, { text: '浪漫', value: 88 }]
  },
  {
    id: 'm26',
    title: '血战钢锯岭',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8a/Hacksaw_Ridge_poster.png',
    genre: [MovieGenre.Action, MovieGenre.Drama],
    releaseDate: '2016-11-04',
    region: MovieRegion.Hollywood,
    director: '梅尔·吉布森',
    actors: ['安德鲁·加菲尔德', '萨姆·沃辛顿'],
    description: '军医戴斯蒙德·多斯赤手空拳救出了75名受伤的战友。',
    rating: 8.7,
    collectCount: 17200,
    ratingDistribution: { 5: 82, 4: 12, 3: 4, 2: 1, 1: 1 },
    keywords: [{ text: '信仰', value: 100 }, { text: '战争', value: 95 }, { text: '真实', value: 90 }, { text: '震撼', value: 85 }]
  },
  {
    id: 'm27',
    title: '这个杀手不太冷',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/0/03/Leon-poster.jpg',
    genre: [MovieGenre.Action, MovieGenre.Crime, MovieGenre.Drama],
    releaseDate: '1994-09-14',
    region: MovieRegion.Europe,
    director: '吕克·贝松',
    actors: ['让·雷诺', '娜塔莉·波特曼', '加里·奥德曼'],
    description: '里昂是名孤独的职业杀手，遇到了邻居小姑娘玛蒂尔达。',
    rating: 9.4,
    collectCount: 22000,
    ratingDistribution: { 5: 88, 4: 10, 1: 1, 2: 1, 3: 1 },
    keywords: [{ text: '救赎', value: 100 }, { text: '孤独', value: 90 }, { text: '盆栽', value: 80 }, { text: '经典', value: 95 }]
  },
  {
    id: 'm28',
    title: '机器人总动员',
    coverUrl: 'https://img.goldposter.com/2015/04/WALL%C2%B7E_poster_goldposter_com_6.jpg?x-oss-process=image/resize,m_fill,h_345,w_236/quality,q_80/format,webp',
    genre: [MovieGenre.Animation, MovieGenre.SciFi, MovieGenre.Romance],
    releaseDate: '2008-06-27',
    region: MovieRegion.Hollywood,
    director: '安德鲁·斯坦顿',
    actors: ['本·贝尔特', '艾丽莎·奈特'],
    description: '孤独的垃圾清理机器人瓦力在废墟中坚持工作了700年。',
    rating: 9.3,
    collectCount: 18500,
    ratingDistribution: { 5: 85, 4: 12, 3: 2, 2: 1, 1: 0 },
    keywords: [{ text: '环保', value: 95 }, { text: '孤独', value: 90 }, { text: '纯真', value: 100 }, { text: '浪漫', value: 95 }]
  },
  {
    id: 'm29',
    title: '绿里奇迹',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e2/The_Green_Mile_%28movie_poster%29.jpg',
    genre: [MovieGenre.Drama, MovieGenre.Crime],
    releaseDate: '1999-12-10',
    region: MovieRegion.Hollywood,
    director: '弗兰克·德拉邦特',
    actors: ['汤姆·汉克斯', '迈克·克拉克·邓肯'],
    description: '狱长保罗这天迎来了一位不平凡的死刑犯——约翰·考夫利。',
    rating: 8.9,
    collectCount: 15400,
    ratingDistribution: { 5: 80, 4: 15, 3: 4, 2: 1, 1: 0 },
    keywords: [{ text: '神迹', value: 95 }, { text: '善良', value: 100 }, { text: '人性', value: 90 }, { text: '泪目', value: 95 }]
  },
  {
    id: 'm30',
    title: '拯救大兵瑞恩',
    coverUrl: 'https://img.goldposter.com/2015/04/Saving-Private-Ryan_poster_goldposter_com_6.jpg?x-oss-process=image/resize,m_fill,h_334,w_236/quality,q_80/format,webp',
    genre: [MovieGenre.Action, MovieGenre.Drama],
    releaseDate: '1998-07-24',
    region: MovieRegion.Hollywood,
    director: '史蒂文·斯皮尔伯格',
    actors: ['汤姆·汉克斯', '马特·达蒙'],
    description: '米勒上尉奉命带领一支小队深入敌后，去寻找并营救瑞恩。',
    rating: 9.1,
    collectCount: 19800,
    ratingDistribution: { 5: 82, 4: 14, 3: 3, 2: 1, 1: 0 },
    keywords: [{ text: '战争', value: 100 }, { text: '写实', value: 95 }, { text: '人性', value: 90 }, { text: '震撼', value: 92 }]
  },
  {
    id: 'm31',
    title: '幽灵公主',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8c/Princess_Mononoke_Japanese_poster.png',
    genre: [MovieGenre.Animation, MovieGenre.Action, MovieGenre.Drama],
    releaseDate: '1997-07-12',
    region: MovieRegion.JapanKorea,
    director: '宫崎骏',
    actors: ['松田洋治', '石田百合子'],
    description: '阿席达卡卷入了人类炼铁场与森林众神之间的惨烈冲突。',
    rating: 8.9,
    collectCount: 16200,
    ratingDistribution: { 5: 80, 4: 16, 3: 3, 2: 1, 1: 0 },
    keywords: [{ text: '自然', value: 100 }, { text: '环保', value: 95 }, { text: '生命', value: 90 }, { text: '壮丽', value: 85 }]
  },
  {
    id: 'm32',
    title: '闪灵',
    coverUrl: 'https://img.goldposter.com/2019/09/the-shining_poster_goldposter_com_126.jpg?x-oss-process=image/resize,m_fill,h_1200,w_800/quality,q_80/format,webp',
    genre: [MovieGenre.Horror, MovieGenre.Drama],
    releaseDate: '1980-05-23',
    region: MovieRegion.Hollywood,
    director: '斯坦利·库布里克',
    actors: ['杰克·尼科尔森', '谢莉·杜瓦尔'],
    description: '大雪封山，酒店内诡异的力量开始侵蚀杰克的理智。',
    rating: 8.6,
    collectCount: 12500,
    ratingDistribution: { 5: 70, 4: 20, 3: 8, 2: 2, 1: 0 },
    keywords: [{ text: '心理恐怖', value: 100 }, { text: '经典', value: 95 }, { text: '库布里克', value: 90 }, { text: '发疯', value: 85 }]
  },
  {
    id: 'm33',
    title: '招魂',
    coverUrl: 'https://img.goldposter.com/2017/12/the-conjuring_poster_goldposter_com_1.jpg?x-oss-process=image/resize,m_fill,h_345,w_236/quality,q_80/format,webp',
    genre: [MovieGenre.Horror],
    releaseDate: '2013-07-19',
    region: MovieRegion.Hollywood,
    director: '温子仁',
    actors: ['维拉·法梅加', '帕特里克·威尔森'],
    description: '接连发生的超自然现象让他们陷入绝望。',
    rating: 8.5,
    collectCount: 11200,
    ratingDistribution: { 5: 65, 4: 25, 3: 7, 2: 3, 1: 0 },
    keywords: [{ text: '温子仁', value: 100 }, { text: '驱魔', value: 90 }, { text: '真实改编', value: 85 }, { text: '恐怖', value: 95 }]
  },
  {
    id: 'm34',
    title: '异形',
    coverUrl: 'https://img.goldposter.com/2015/01/Ailen-poster-goldposter-com003.jpg?x-oss-process=image/resize,m_fill,h_340,w_236/quality,q_80/format,webp',
    genre: [MovieGenre.Horror, MovieGenre.SciFi],
    releaseDate: '1979-05-25',
    region: MovieRegion.Hollywood,
    director: '雷德利·斯科特',
    actors: ['西格妮·韦弗', '汤姆·斯凯里特'],
    description: '外星生物开始在封闭的飞船中展开猎杀。',
    rating: 8.7,
    collectCount: 13800,
    ratingDistribution: { 5: 75, 4: 18, 3: 5, 2: 1, 1: 1 },
    keywords: [{ text: '太空恐怖', value: 100 }, { text: '经典', value: 95 }, { text: '异形', value: 90 }, { text: '密闭空间', value: 85 }]
  },
  {
    id: 'm35',
    title: '逃出绝命镇',
    coverUrl: 'https://img.goldposter.com/2017/12/get-out_poster_goldposter_com_15.jpg?x-oss-process=image/resize,m_fill,h_1500,w_1034/quality,q_80/format,webp',
    genre: [MovieGenre.Horror, MovieGenre.Crime],
    releaseDate: '2017-02-24',
    region: MovieRegion.Hollywood,
    director: '乔丹·皮尔',
    actors: ['丹尼尔·卡卢亚', '艾莉森·威廉姆斯'],
    description: '黑人青年克里斯发现自己陷入了一个恐怖的阴谋之中。',
    rating: 8.3,
    collectCount: 14500,
    ratingDistribution: { 5: 60, 4: 25, 3: 10, 2: 4, 1: 1 },
    keywords: [{ text: '社会讽刺', value: 100 }, { text: '反转', value: 95 }, { text: '心理', value: 90 }, { text: '黑马', value: 85 }]
  },
  {
    id: 'm36',
    title: '辛德勒的名单',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg',
    genre: [MovieGenre.Drama, MovieGenre.Crime],
    releaseDate: '1993-12-15',
    region: MovieRegion.Hollywood,
    director: '史蒂文·斯皮尔伯格',
    actors: ['连姆·尼森', '本·金斯利', '拉尔夫·费因斯'],
    description: '辛德勒倾家荡产保护了1200余名犹太人免遭纳粹杀害。',
    rating: 9.6,
    collectCount: 18200,
    ratingDistribution: { 5: 94, 4: 4, 3: 1, 2: 1, 1: 0 },
    keywords: [{ text: '人性', value: 100 }, { text: '救赎', value: 95 }, { text: '战争', value: 90 }, { text: '黑白', value: 80 }]
  },
  {
    id: 'm37',
    title: '七宗罪',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg',
    genre: [MovieGenre.Crime, MovieGenre.Drama],
    releaseDate: '1995-09-22',
    region: MovieRegion.Hollywood,
    director: '大卫·芬奇',
    actors: ['布拉德·皮特', '摩根·弗里曼', '凯文·史派西'],
    description: '天主教教义所指的人类七种罪恶，演变成了一连串精心策划的连环杀人案。',
    rating: 8.8,
    collectCount: 14500,
    ratingDistribution: { 5: 78, 4: 15, 3: 5, 2: 2, 1: 0 },
    keywords: [{ text: '犯罪', value: 95 }, { text: '压抑', value: 90 }, { text: '反转', value: 100 }, { text: '芬奇', value: 85 }]
  },
  {
    id: 'm38',
    title: '惊魂记',
    coverUrl: 'https://img.goldposter.com/2015/04/Psycho_poster_goldposter_com_6.jpg?x-oss-process=image/resize,m_fill,h_327,w_236/quality,q_80/format,webp',
    genre: [MovieGenre.Horror, MovieGenre.Drama],
    releaseDate: '1960-06-16',
    region: MovieRegion.Hollywood,
    director: '阿尔弗雷德·希区柯克',
    actors: ['安东尼·博金斯', '珍妮特·利'],
    description: '浴室里的尖叫声成为了恐怖电影永恒的经典。',
    rating: 9.0,
    collectCount: 11000,
    ratingDistribution: { 5: 80, 4: 14, 3: 4, 2: 2, 1: 0 },
    keywords: [{ text: '悬疑', value: 100 }, { text: '希区柯克', value: 95 }, { text: '经典', value: 90 }, { text: '浴室', value: 85 }]
  },
  {
    id: 'm39',
    title: '银翼杀手2049',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png',
    genre: [MovieGenre.SciFi, MovieGenre.Action],
    releaseDate: '2017-10-06',
    region: MovieRegion.Hollywood,
    director: '丹尼斯·维伦纽瓦',
    actors: ['瑞恩·高斯林', '哈里森·福特'],
    description: '一名新的银翼杀手K揭开了一个深藏已久的秘密。',
    rating: 8.5,
    collectCount: 15600,
    ratingDistribution: { 5: 65, 4: 25, 3: 8, 2: 2, 1: 0 },
    keywords: [{ text: '赛博朋克', value: 100 }, { text: '科幻', value: 95 }, { text: '视觉盛宴', value: 90 }, { text: '哲学', value: 85 }]
  }
];

/**
 * 模拟评论数据
 */
export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    movieId: 'm1',
    userId: '2',
    username: '电影发烧友',
    userAvatar: 'https://ui-avatars.com/api/?name=User&background=random',
    content: '这绝对是影史最佳，没有之一！特别是最后逃出来的那个镜头，太震撼了。自由万岁！',
    timestamp: Date.now() - 10000000,
    likes: 342
  },
  {
    id: 'c2',
    movieId: 'm1',
    userId: '1',
    username: '管理员',
    userAvatar: 'https://ui-avatars.com/api/?name=Admin&background=random',
    content: '同感，配乐也非常经典。',
    timestamp: Date.now() - 9000000,
    parentId: 'c1',
    likes: 56
  }
];

/**
 * 模拟新闻资讯
 */
export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'n2025_01',
    title: '第97届奥斯卡金像奖揭晓：奉俊浩新作横扫技术奖',
    summary: '2025年奥斯卡颁奖礼落下帷幕。在充满竞争的一年中，几部硬核科幻作品在视觉效果和音效设计上实现了历史性突破。',
    coverUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&q=80&w=1280',
    date: '2025-03-24',
    tag: '颁奖季'
  }
];

/**
 * 表情包备选列表
 */
export const EMOJIS = ['👍', '👎', '❤️', '😂', '😮', '😢', '😡', '🔥', '🍿', '🎬'];